name: Build

on: 
  push:
    branches:
      - master
      - whitelist
  pull_request:
    branches:
      - master

jobs:
    build:
        name: Build
        runs-on: macOS-12
        steps:
        - name: Select Xcode
          run: xcversion select 13.3.1

        - name: Check XCode Version
          run: xcodebuild -version

        - name: Checkout
          uses: actions/checkout@v4

        - name: macOS Native
          run: swift test
